from __future__ import annotations

import re
from pathlib import Path

from tests.conftest import invoke_json, invoke_json_may_fail


def _write_sphinx_project(project: Path, runner, *, command: str | None) -> bytes:
    docs = project / "docs"
    docs.mkdir(exist_ok=True)
    (docs / "conf.py").write_text(
        "project = 'verification fixture'\nextensions = ['myst_parser']\nmyst_enable_extensions = ['colon_fence']\n",
        encoding="utf-8",
    )
    (docs / "requirements.txt").write_text("sphinx\nmyst-parser\n", encoding="utf-8")
    (docs / "index.md").write_text(
        "# Package documentation\n\n"
        "```{toctree}\n:maxdepth: 2\n\nchangelog\n```\n\n"
        "<!-- docledger-section: api -->\n## API\n\nThe package exposes the documented CLI and API.\n",
        encoding="utf-8",
    )
    changelog_bytes = (
        b"<!-- generated by releaseledger -->\n# Changelog\n\n"
        b"<!-- docledger-section: releases -->\n## Releases\n\n- Existing release entry.\n"
    )
    (docs / "changelog.md").write_bytes(changelog_bytes)
    invoke_json(runner, ["init"])

    config_path = project / ".ledger" / "documentledger" / "config.toml"
    config = config_path.read_text(encoding="utf-8")
    config = config.replace('doc_roots = ["docs", "README.md"]', 'doc_roots = ["docs"]')
    if command:
        config = config.replace("commands = []", f'commands = ["{command}"]')
    config_path.write_text(config, encoding="utf-8")
    invoke_json(runner, ["scan"])
    return changelog_bytes


def test_clean_baseline_is_not_documentation_completion_and_strict_gates_are_opt_in(project: Path, runner) -> None:
    invoke_json(runner, ["init"])
    invoke_json(runner, ["scan"])

    status = invoke_json(runner, ["status"])["result"]
    assert status["freshness_state"] == "clean"
    assert status["health"]["state"] == "healthy"
    assert status["mapping"]["state"] == "review_required"
    assert status["completion"]["ready"] is False
    assert "mapping_coverage_incomplete" in status["completion"]["blocking_reasons"]


def test_intentionally_unlinked_document_resolution_is_inspectable_and_content_bound(project: Path, runner) -> None:
    invoke_json(runner, ["init"])
    invoke_json(runner, ["scan"])
    invoke_json(
        runner,
        [
            "document",
            "mark-fresh",
            "--doc",
            "README.md",
            "--allow-unlinked",
            "--reason",
            "Reviewed as intentionally outside generated package documentation.",
        ],
    )

    coverage = invoke_json(runner, ["coverage"])["result"]["mapping"]["documents"]
    assert coverage["intentionally_unlinked"] == 1
    assert coverage["unresolved"] == 0
    decision = coverage["classifications"][0]
    assert decision["state"] == "intentionally_unlinked"
    assert "Reviewed as intentionally outside" in decision["reason"]

    readme = project / "README.md"
    readme.write_text(readme.read_text(encoding="utf-8") + "\nChanged after explicit review.\n", encoding="utf-8")
    invoke_json(runner, ["scan"])
    updated = invoke_json(runner, ["status"])["result"]["mapping"]["documents"]
    assert updated["intentionally_unlinked"] == 0
    assert updated["unresolved"] == 1

    exit_code, result = invoke_json_may_fail(runner, ["check", "--complete"])
    assert exit_code != 0
    assert result["error"]["code"] == "check-failed"
    assert result["error"]["details"]["readiness"]["completion"]["ready"] is False


def test_doctor_and_config_validate_have_backward_compatible_strict_modes(project: Path, runner) -> None:
    invoke_json(runner, ["init"])
    config_path = project / ".ledger" / "documentledger" / "config.toml"
    config = config_path.read_text(encoding="utf-8")
    config = re.sub(r"source_roots = \[[^\]]*\]", 'source_roots = ["missing-package"]', config, count=1)
    config_path.write_text(config, encoding="utf-8")

    doctor = invoke_json(runner, ["doctor"])
    assert doctor["ok"] is True
    assert doctor["result"]["ok"] is False
    exit_code, strict_doctor = invoke_json_may_fail(runner, ["doctor", "--strict"])
    assert exit_code != 0
    assert strict_doctor["error"]["code"] == "doctor-failed"

    config_result = invoke_json(runner, ["config", "validate"])
    assert config_result["result"]["ok"] is False
    exit_code, strict_config = invoke_json_may_fail(runner, ["config", "validate", "--strict"])
    assert exit_code != 0
    assert strict_config["error"]["code"] == "config-validation-failed"


def test_sphinx_attestation_binds_current_hashes_and_failed_build_invalidates_pass(project: Path, runner) -> None:
    sphinx_command = "python -m sphinx -b html -n -W --keep-going docs docs/_build/html"
    changelog_before = _write_sphinx_project(project, runner, command=sphinx_command)
    validation = invoke_json(runner, ["document", "validate"])["result"]
    assert validation["state"] == "passed_current"
    assert validation["attestation"]["schema"] == "documentledger.validation-attestation.v1"
    assert validation["attestation"]["result"] == "passed"
    assert validation["attestation"]["snapshot"]["document_hash"]
    assert validation["attestation"]["snapshot"]["config_hash"]

    status = invoke_json(runner, ["status"])["result"]
    assert status["documentation"]["sphinx_detected"] is True
    assert status["documentation"]["sphinx_build_configured"] is True
    assert status["documentation"]["validation_verified_for_current_content"] is True

    index = project / "docs" / "index.md"
    index.write_text(index.read_text(encoding="utf-8") + "\nUpdated after the build.\n", encoding="utf-8")
    stale = invoke_json(runner, ["status"])["result"]["documentation"]
    assert stale["validation_state"] == "stale"
    assert stale["validation_verified_for_current_content"] is False
    assert stale["scan_matches_current"] is False

    config_path = project / ".ledger" / "documentledger" / "config.toml"
    config = config_path.read_text(encoding="utf-8")
    config = config.replace(
        sphinx_command,
        "python -m sphinx -b html -n -W --keep-going docs docs/_build/html --invalid-option",
    )
    config_path.write_text(config, encoding="utf-8")
    exit_code, failure = invoke_json_may_fail(runner, ["document", "validate"])
    assert exit_code != 0
    assert failure["error"]["code"] == "validation-command-failed"
    failed = invoke_json(runner, ["status"])["result"]["documentation"]
    assert failed["validation_state"] == "failed"
    assert failed["validation_verified_for_current_content"] is False
    assert (project / "docs" / "changelog.md").read_bytes() == changelog_before


def test_sphinx_completion_gate_requires_navigation_coverage_and_current_validation(project: Path, runner) -> None:
    changelog_before = _write_sphinx_project(
        project,
        runner,
        command="python -m sphinx -b html -n -W --keep-going docs docs/_build/html",
    )
    source_ids = invoke_json(runner, ["source", "list", "--ids-only", "--limit", "100"])["result"]["sources"]
    docs = invoke_json(runner, ["document", "sections", "--all", "--ids-only"])["result"]["docs"]
    assert source_ids
    for doc in docs:
        for section_id in doc["sections"]:
            for source_id in source_ids:
                invoke_json(
                    runner,
                    [
                        "link",
                        "add-section",
                        "--doc",
                        doc["doc_path"],
                        "--section",
                        section_id,
                        "--source-unit",
                        source_id,
                        "--coverage",
                        "cli-command",
                        "--impact",
                        "behavior",
                        "--reason",
                        "Reviewed documentation completion fixture mapping.",
                    ],
                )

    invoke_json(runner, ["document", "mark-fresh", "--all", "--reason", "Strict Sphinx build and mapping review passed."])
    invoke_json(runner, ["document", "validate"])
    checked = invoke_json(runner, ["check", "--complete"])["result"]
    assert checked["ok"] is True
    assert checked["readiness"]["mapping"]["state"] == "covered"
    assert checked["readiness"]["documentation"]["navigation_ready"] is True
    assert checked["readiness"]["completion"]["ready"] is True
    assert (project / "docs" / "changelog.md").read_bytes() == changelog_before


def test_skipped_sphinx_validation_cannot_attest_completion(project: Path, runner) -> None:
    _write_sphinx_project(project, runner, command=None)
    result = invoke_json(runner, ["document", "validate"])["result"]
    assert result["state"] == "not_configured"
    status = invoke_json(runner, ["status"])["result"]["documentation"]
    assert status["validation_required"] is True
    assert status["validation_configured"] is False
    assert status["validation_verified_for_current_content"] is False
    exit_code, checked = invoke_json_may_fail(runner, ["check", "--complete"])
    assert exit_code != 0
    assert checked["error"]["code"] == "check-failed"
    assert "validation_not_configured" in checked["error"]["details"]["readiness"]["completion"]["blocking_reasons"]
