from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path
from typing import Any

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
CLI_BOOTSTRAP = "from documentledger.cli import app; app()"


def _write_fixture(project: Path) -> bytes:
    (project / "audioexport").mkdir(parents=True)
    (project / "tests").mkdir()
    docs = project / "docs"
    (docs / "api").mkdir(parents=True)
    (project / "pyproject.toml").write_text(
        "[project]\nname = 'audioexport'\nversion = '0.1.0'\nrequires-python = '>=3.11'\n",
        encoding="utf-8",
    )
    (project / "README.md").write_text("# Sample workspace\n\nA workspace fixture.\n", encoding="utf-8")
    (project / "audioexport" / "__init__.py").write_text(
        "from .api import export_audio, inspect_audio\n\n__all__ = ['export_audio', 'inspect_audio']\n",
        encoding="utf-8",
    )
    (project / "audioexport" / "api.py").write_text(
        '"""Public audio export API."""\n\n'
        "def export_audio(source: str, target: str) -> str:\n"
        '    """Export one audio source to a target path."""\n'
        "    return target\n\n\n"
        "def inspect_audio(source: str) -> dict[str, str]:\n"
        '    """Return basic metadata for an audio source."""\n'
        '    return {"source": source}\n',
        encoding="utf-8",
    )
    (project / "audioexport" / "cli.py").write_text(
        '"""Command-line interface for audioexport."""\n\n'
        "import argparse\n\n\n"
        "def build_parser() -> argparse.ArgumentParser:\n"
        '    """Create the audioexport command parser."""\n'
        "    parser = argparse.ArgumentParser(prog='audioexport')\n"
        "    parser.add_argument('--output', required=True)\n"
        "    parser.add_argument('--format', choices=('wav', 'mp3'), default='wav')\n"
        "    return parser\n\n\n"
        "def main(argv: list[str] | None = None) -> int:\n"
        '    """Parse one audioexport command."""\n'
        "    build_parser().parse_args(argv)\n"
        "    return 0\n",
        encoding="utf-8",
    )
    (project / "tests" / "test_api.py").write_text(
        "from audioexport.api import export_audio\n\n\n"
        "def test_export_audio_returns_target() -> None:\n"
        "    assert export_audio('input.wav', 'output.wav') == 'output.wav'\n",
        encoding="utf-8",
    )
    (docs / "requirements.txt").write_text("sphinx>=8\nmyst-parser\n", encoding="utf-8")
    (docs / "conf.py").write_text(
        "project = 'pykokoro'\nextensions = ['myst_parser']\nmyst_enable_extensions = ['colon_fence']\n",
        encoding="utf-8",
    )
    changelog = (
        b"<!-- Generated by Releaseledger; preserve this file's content. -->\n"
        b"# Changelog\n\n"
        b"## Existing release\n\n"
        b"- Existing release notes owned by the release workflow.\n"
    )
    (docs / "changelog.md").write_bytes(changelog)

    import ledgercore
    from ledgercore.manifest import LedgerProjectManifest, LedgerRegistration, MountDefinition

    other = LedgerRegistration(name="otherledger", mounts={"state": MountDefinition(name="state", storage="project")})
    manifest = LedgerProjectManifest(
        schema_version=3,
        project_uuid="11111111-1111-4111-8111-111111111111",
        project_name="audioexport-fixture",
        ledgers={"otherledger": other},
    )
    ledgercore.write_ledger_manifest(project / ".ledger" / "ledger.toml", manifest)
    return changelog


def _env(project: Path, shim: Path, *, fail_tmp_output: bool = False) -> dict[str, str]:
    env = dict(os.environ)
    existing = env.get("PYTHONPATH", "")
    parts = [str(shim), str(REPO_ROOT)]
    if existing:
        parts.append(existing)
    env["PYTHONPATH"] = os.pathsep.join(parts)
    if fail_tmp_output:
        env["DOCUMENTLEDGER_TEST_FAIL_TMP_OUTPUT"] = "1"
    else:
        env.pop("DOCUMENTLEDGER_TEST_FAIL_TMP_OUTPUT", None)
    env["PYTHONDONTWRITEBYTECODE"] = "1"
    return env


def _invoke(project: Path, shim: Path, *args: str, fail_tmp_output: bool = False) -> dict[str, Any]:
    completed = subprocess.run(
        [sys.executable, "-c", CLI_BOOTSTRAP, "--json", *args],
        cwd=project,
        env=_env(project, shim, fail_tmp_output=fail_tmp_output),
        capture_output=True,
        text=True,
        check=False,
    )
    try:
        payload = json.loads(completed.stdout)
    except json.JSONDecodeError as exc:
        raise AssertionError(f"CLI did not return JSON (exit {completed.returncode}): {completed.stdout}\n{completed.stderr}") from exc
    if completed.returncode == 0:
        assert payload["ok"] is True, payload
    return payload


def _invoke_raw(project: Path, shim: Path, *args: str) -> str:
    completed = subprocess.run(
        [sys.executable, "-c", CLI_BOOTSTRAP, *args],
        cwd=project,
        env=_env(project, shim),
        capture_output=True,
        text=True,
        check=False,
    )
    assert completed.returncode == 0, f"{completed.stdout}\n{completed.stderr}"
    return completed.stdout


def _configure_validation(project: Path) -> None:
    config_path = project / ".ledger" / "documentledger" / "config.toml"
    config = config_path.read_text(encoding="utf-8")
    command = "python -m sphinx -b html -n -W --keep-going docs docs/_build/html"
    config = config.replace("commands = []", f'commands = ["{command}"]')
    config_path.write_text(config, encoding="utf-8")


def _write_documentation(project: Path) -> None:
    docs = project / "docs"
    (docs / "conf.py").write_text(
        "project = 'audioexport'\nextensions = ['myst_parser']\nmyst_enable_extensions = ['colon_fence']\n",
        encoding="utf-8",
    )
    (docs / "index.md").write_text(
        "# audioexport documentation\n\n```{toctree}\n:maxdepth: 2\n\napi/index\ncli\nguide\nchangelog\n```\n",
        encoding="utf-8",
    )
    (docs / "api" / "index.md").write_text(
        "# API reference\n\n## Public audio API\n\n`export_audio` writes a converted asset, and `inspect_audio` returns source metadata.\n",
        encoding="utf-8",
    )
    (docs / "cli.md").write_text(
        "# Command-line reference\n\n## Export options\n\nUse `audioexport --output PATH --format wav` to export an audio file.\n",
        encoding="utf-8",
    )
    (docs / "guide.md").write_text(
        "# Project guide\n\nGeneral workflow guidance for maintainers.\n",
        encoding="utf-8",
    )


def _all_source_units(project: Path, shim: Path) -> list[dict[str, Any]]:
    result = _invoke(project, shim, "source", "list", "--limit", "100")["result"]
    assert result["next_cursor"] is None
    return result["sources"]


def _refresh_doc(project: Path, shim: Path, doc_path: str, *, intentionally_unlinked: bool = False) -> None:
    command = ["document", "mark-fresh", "--doc", doc_path, "--reason", "Reviewed after strict Sphinx validation."]
    if intentionally_unlinked:
        command.append("--allow-unlinked")
    _invoke(project, shim, *command)


def test_audioexport_shaped_sphinx_bootstrap_recovery_and_incremental_workflow(tmp_path: Path) -> None:
    pytest.importorskip("sphinx")
    pytest.importorskip("myst_parser")
    project = tmp_path / "sample_project"
    project.mkdir()
    original_changelog = _write_fixture(project)
    shim = tmp_path / "python-shim"
    shim.mkdir()
    (shim / "sitecustomize.py").write_text(
        "import os\n"
        "from pathlib import Path\n"
        "from documentledger import output\n"
        "_write_output_file = output.write_output_file\n"
        "def _fail_requested_tmp_output(path, writer, *, command, managed_artifact):\n"
        "    if os.environ.get('DOCUMENTLEDGER_TEST_FAIL_TMP_OUTPUT') == '1' and Path(path) == Path('/tmp/context.md'):\n"
        "        raise output.output_write_error(\n"
        "            path,\n"
        "            command=command,\n"
        "            cause=PermissionError(13, 'fixture denies /tmp'),\n"
        "            managed_artifact=managed_artifact,\n"
        "        )\n"
        "    return _write_output_file(path, writer, command=command, managed_artifact=managed_artifact)\n"
        "output.write_output_file = _fail_requested_tmp_output\n",
        encoding="utf-8",
    )

    initialized = _invoke(project, shim, "init")["result"]
    assert initialized["source_root_discovery"]["production_roots"] == ["audioexport"]
    assert initialized["source_root_discovery"]["test_roots"] == ["tests"]
    from ledgercore import load_ledger_project

    registrations = load_ledger_project(project).manifest.ledgers
    assert set(registrations) == {"otherledger", "documentledger"}
    config_path = project / ".ledger" / "documentledger" / "config.toml"
    config_text = config_path.read_text(encoding="utf-8")
    assert 'source_roots = ["audioexport", "tests"]' in config_text
    assert '"documentledger"' not in config_text

    status = _invoke(project, shim, "status")["result"]
    doctor = _invoke(project, shim, "doctor")["result"]
    assert status["completion"]["ready"] is False
    assert doctor["ok"] is True
    assert not any(issue["code"] == "package_root_not_configured" for issue in doctor["issues"])

    baseline = _invoke(project, shim, "scan")["result"]
    assert baseline["version"] == 1
    assert _invoke(project, shim, "status")["result"]["completion"]["ready"] is False

    output_failure = _invoke(
        project,
        shim,
        "document",
        "build-context",
        "--bootstrap",
        "--out",
        "/tmp/context.md",
        fail_tmp_output=True,
    )
    assert output_failure["ok"] is False
    assert output_failure["error"]["code"] == "output-write-failed"
    assert output_failure["error"]["details"]["errno_name"] == "EACCES"
    assert "--out -" in " ".join(output_failure["error"]["remediation"])
    recovered_context = _invoke_raw(project, shim, "document", "build-context", "--bootstrap", "--out", "-")
    assert "DOCUMENTLEDGER CONTEXT: COMPLETE" in recovered_context
    assert "truncated: false" in recovered_context

    _write_documentation(project)
    _configure_validation(project)
    assert (project / "docs" / "changelog.md").read_bytes() == original_changelog
    _invoke(project, shim, "scan")

    stale_dir = project / "stale-proposals"
    _invoke(project, shim, "link", "propose", "--all-docs", "--out-dir", str(stale_dir))
    stale_manifest = stale_dir / "proposal-manifest.yaml"
    _invoke(project, shim, "link", "import-map", "--directory", str(stale_dir), "--review")
    cli_source = project / "audioexport" / "cli.py"
    cli_source.write_text(cli_source.read_text(encoding="utf-8").replace("--format", "--format-name"), encoding="utf-8")
    cli_doc = project / "docs" / "cli.md"
    cli_doc.write_text(cli_doc.read_text(encoding="utf-8").replace("--format", "--format-name"), encoding="utf-8")
    _invoke(project, shim, "scan")
    stale_import = _invoke(project, shim, "link", "import-map", "--directory", str(stale_dir), "--check-and-apply")
    assert stale_import["ok"] is False
    assert stale_import["error"]["code"] == "proposal-manifest-stale"
    assert stale_manifest.is_file()

    proposal_dir = project / "reviewed-proposals"
    proposal_result = _invoke(project, shim, "link", "propose", "--all-docs", "--out-dir", str(proposal_dir))["result"]
    import yaml

    manifest_path = proposal_dir / "proposal-manifest.yaml"
    manifest = yaml.safe_load(manifest_path.read_text(encoding="utf-8"))
    proposal_names = {entry["doc_path"]: entry["filename"] for entry in manifest["documents"]}
    assert proposal_names["docs/index.md"] != proposal_names["docs/api/index.md"]
    assert any(entry["outcome"] == "no_candidates" for entry in manifest["documents"])
    assert proposal_result["collisions"] == 0
    unowned_map = proposal_dir / "obsolete-user-map.yaml"
    unowned_bytes = b"this stale user file is not owned by the proposal manifest\n"
    unowned_map.write_bytes(unowned_bytes)
    _invoke(project, shim, "link", "import-map", "--directory", str(proposal_dir), "--review")
    imported = _invoke(project, shim, "link", "import-map", "--directory", str(proposal_dir), "--check-and-apply")["result"]
    assert "obsolete-user-map.yaml" in imported["unowned_mapping_files"]
    assert unowned_map.read_bytes() == unowned_bytes

    # Keep the reviewed proposal/import path in the fixture, then replace its
    # broad automated suggestions with explicit section-level fixture evidence.
    records = _invoke(project, shim, "link", "list")["result"]["docs"]
    for record in records:
        for section in record.get("sections", []):
            for link in section.get("links", []):
                _invoke(
                    project,
                    shim,
                    "link",
                    "remove-section",
                    "--doc",
                    record["doc_path"],
                    "--section",
                    str(section["section_id"]),
                    "--source-unit",
                    str(link["source_id"]),
                )

    units = _all_source_units(project, shim)
    sections = _invoke(project, shim, "document", "sections", "--all", "--ids-only")["result"]["docs"]
    relevant_docs = {"docs/api/index.md": "api", "docs/cli.md": "cli"}
    added_units: set[str] = set()
    for doc in sections:
        group = relevant_docs.get(doc["doc_path"])
        if group is None:
            continue
        for section_id in doc["sections"]:
            for unit in units:
                path = str(unit.get("path", ""))
                unit_group = "cli" if path.endswith("/cli.py") else "api"
                if unit_group != group:
                    continue
                _invoke(
                    project,
                    shim,
                    "link",
                    "add-section",
                    "--doc",
                    doc["doc_path"],
                    "--section",
                    section_id,
                    "--source-unit",
                    str(unit["source_id"]),
                    "--coverage",
                    "cli-command",
                    "--impact",
                    "behavior",
                    "--reason",
                    "Reviewed fixture source-to-section mapping.",
                )
                added_units.add(str(unit["source_id"]))
    assert added_units == {str(unit["source_id"]) for unit in units}
    audit = _invoke(project, shim, "link", "audit")["result"]
    assert audit["ok"] is True

    validation = _invoke(project, shim, "document", "validate")["result"]
    assert validation["state"] == "passed_current"
    build_root = project / "docs" / "_build" / "html"
    assert (build_root / "index.html").is_file()
    assert (build_root / "changelog.html").is_file()
    assert b"changelog.html" in (build_root / "index.html").read_bytes()
    assert (project / "docs" / "changelog.md").read_bytes() == original_changelog

    intentional_docs = {"README.md", "docs/index.md", "docs/guide.md", "docs/changelog.md"}
    for doc in sections:
        doc_path = str(doc["doc_path"])
        if doc_path in relevant_docs:
            _refresh_doc(project, shim, doc_path)
        else:
            assert doc_path in intentional_docs
            _refresh_doc(project, shim, doc_path, intentionally_unlinked=True)
    completed = _invoke(project, shim, "check", "--complete")["result"]
    assert completed["readiness"]["completion"]["ready"] is True
    assert completed["readiness"]["mapping"]["sources"]["units_unlinked"] == 0
    assert completed["readiness"]["mapping"]["documents"]["unresolved"] == 0
    assert completed["readiness"]["documentation"]["navigation_ready"] is True
    status_complete = _invoke(project, shim, "status")["result"]
    assert status_complete["completion"]["ready"] is True

    api_page_before = (project / "docs" / "api" / "index.md").read_bytes()
    cli_source.write_text(cli_source.read_text(encoding="utf-8") + "\n# Public CLI option changed.\n", encoding="utf-8")
    _invoke(project, shim, "scan")
    affected = _invoke(project, shim, "document", "affected")["result"]["affected_sections"]
    assert affected
    assert {item["doc_path"] for item in affected} == {"docs/cli.md"}
    context = _invoke_raw(project, shim, "document", "build-context", "--doc", "docs/cli.md", "--out", "-")
    assert "DOCUMENTLEDGER CONTEXT: COMPLETE" in context
    cli_doc.write_text(cli_doc.read_text(encoding="utf-8") + "\nThe updated option is `--format-name`.\n", encoding="utf-8")
    _invoke(project, shim, "scan")
    assert (project / "docs" / "api" / "index.md").read_bytes() == api_page_before
    for doc_path in relevant_docs:
        _refresh_doc(project, shim, doc_path)
    for doc_path in sorted(intentional_docs):
        _refresh_doc(project, shim, doc_path, intentionally_unlinked=True)
    updated_validation = _invoke(project, shim, "document", "validate")["result"]
    assert updated_validation["state"] == "passed_current"
    updated_check = _invoke(project, shim, "check", "--complete")["result"]
    assert updated_check["readiness"]["completion"]["ready"] is True
    assert (project / "docs" / "changelog.md").read_bytes() == original_changelog

    config = config_path.read_text(encoding="utf-8")
    valid_command = "python -m sphinx -b html -n -W --keep-going docs docs/_build/html"
    config_path.write_text(
        config.replace(valid_command, valid_command + " --invalid-option"),
        encoding="utf-8",
    )
    failed_validation = _invoke(project, shim, "document", "validate")
    assert failed_validation["ok"] is False
    assert failed_validation["error"]["code"] == "validation-command-failed"
    failed_status = _invoke(project, shim, "status")["result"]
    assert failed_status["documentation"]["validation_state"] == "failed"
    assert failed_status["completion"]["ready"] is False
    failed_check = _invoke(project, shim, "check", "--complete")
    assert failed_check["ok"] is False
    assert failed_check["error"]["details"]["readiness"]["completion"]["ready"] is False
    assert (project / "docs" / "changelog.md").read_bytes() == original_changelog
