#!/usr/bin/env python3
"""Generate the stable Markdown CLI reference from command metadata and Click."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

from click import Argument, Command
from typer.main import get_command

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "cli.md"


def _command_for(root: Command, path: str) -> Command:
    command: Any = root
    for name in path.split():
        command = command.commands[name]
    return command


def _default(value: Any) -> str:
    if value is None or value is False:
        return ""
    return repr(value)


def _parameters(command: Command) -> str:
    if not command.params:
        return "- None."
    rows = ["| Parameter | Required | Default | Type |", "| --- | --- | --- | --- |"]
    for parameter in command.params:
        if isinstance(parameter, Argument):
            name = parameter.name
        else:
            name = ", ".join(parameter.opts)
        kind = getattr(parameter.type, "name", str(parameter.type))
        rows.append(f"| `{name}` | {'yes' if parameter.required else 'no'} | `{_default(parameter.default)}` | `{kind}` |")
    return "\n".join(rows)


def render() -> str:
    from documentledger.cli import app
    from documentledger.command_catalog import COMMAND_INVENTORY

    root = get_command(app)
    canonical_reference_intro = (
        "This is the authoritative canonical command reference. "
        "It is generated from `COMMAND_INVENTORY` and the registered Click command tree; "
        "run the generator check in CI after command changes."
    )
    json_contract_description = (
        "With `--json`, the command returns `ok`, `command`, a command-specific `result`, "
        "and `events`. Failures return the normalized `error` object with `code`, `message`, "
        "`remediation`, and `details.domain_code`. Invalid workspace, selector, cursor, link, "
        "or migration state is reported before a write when applicable."
    )
    lines = [
        "# CLI reference",
        "",
        "<!-- This file is generated by scripts/generate_cli_reference.py. -->",
        "",
        canonical_reference_intro,
        "",
        "## Global options",
        "",
        "Global options may appear before the command path:",
        "",
        "| Option | Effect |",
        "| --- | --- |",
        "| `--root PATH` | Resolve the project from PATH instead of the current directory. |",
        "| `--json` | Emit the stable JSON envelope. |",
        "| `--profile` | Include diagnostic operation events in JSON output. |",
        "| `--version` | Show the installed version. |",
        "| `--install-completion` | Install shell completion. |",
        "| `--show-completion` | Print shell completion. |",
        "",
        "## Canonical commands",
        "",
    ]
    for entry in COMMAND_INVENTORY.entries:
        command = _command_for(root, entry.path)
        aliases = ", ".join(f"`{alias}`" for alias in entry.aliases) or "None"
        workspace = "yes" if entry.requires_workspace else "no"
        lines.extend(
            [
                f"## {entry.path}",
                "",
                entry.summary,
                "",
                f"- **Effect:** `{entry.effect}`",
                f"- **Audience:** `{entry.audience}`",
                f"- **Workspace required:** `{workspace}`",
                f"- **Targeting:** `{entry.targeting}`",
                f"- **Compatibility aliases:** {aliases}",
                "",
                "### Syntax",
                "",
                f"```bash\ndocumentledger {entry.path}\n```",
                "",
                "### Arguments and options",
                "",
                _parameters(command),
                "",
                "### JSON result and errors",
                "",
                json_contract_description,
                "",
                "### Example",
                "",
                f"```bash\ndocumentledger {entry.path}\n```",
                "",
            ]
        )
    lines.extend(
        [
            "## Compatibility commands",
            "",
            "Compatibility interfaces are documented separately and are not canonical inventory entries:",
            "",
            "| Compatibility path | Use instead |",
            "| --- | --- |",
            "| `docledger` executable | `documentledger` |",
            "| `docs ...` | `document ...` |",
            "| `sources ...` | `source ...` |",
            "| `links ...` | `link ...` |",
            "| root `mark-fresh` | `document mark-fresh` |",
            "| `storage verify` | `storage validate` |",
            "| `storage migrate` | `migrate plan` or `migrate apply` |",
            "| `storage recover` | `migrate recover` |",
            "| `storage cleanup-legacy` | `migrate cleanup` |",
            "",
            ":::{deprecated} 0.6",
            "These wrappers remain for compatibility and may emit deprecation warnings. New automation must use canonical command paths.",
            ":::",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the checked-in reference differs")
    args = parser.parse_args()
    rendered = render()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != rendered:
            print(f"{OUTPUT} is out of date; run python scripts/generate_cli_reference.py", file=sys.stderr)
            return 1
        print(f"{OUTPUT} is up to date")
        return 0
    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
